# Site
name: "Data Dilemmas and Discussions"
title: "Data Dilemmas and Discussions"
description: "This blog explores my different interests in data science and catalog my projects. Thanks for stopping by!"
logo: 'assets/images/SelfieCircle.png'
favicon: 'assets/images/SelfieCircle.png'
baseurl: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  lucy:
    name: Lucy
    display_name: Lucy
    # gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: lucystorts@gmail.com
    web: lucystorts.github.io/BlogRepo/
    # twitter: https://twitter.com/wowthemesnet
    description: "Blog Author"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
